using System;
using System.Collections.Generic;

namespace MSC.UI.Presentation
{
    internal sealed class UiTextCatalog
    {
        private readonly Dictionary<string, Entry> entries =
            new Dictionary<string, Entry>(StringComparer.Ordinal)
            {
                ["ui.save_status.recovered_backup"] = new Entry("A VALID BACKUP WAS RECOVERED", "ВОССТАНОВЛЕНА КОРРЕКТНАЯ РЕЗЕРВНАЯ КОПИЯ"),
                ["ui.save_status.recovered_interrupted"] = new Entry("AN INTERRUPTED SAVE WRITE WAS RECOVERED", "ВОССТАНОВЛЕНО ПРЕРВАННОЕ СОХРАНЕНИЕ"),
                ["ui.notice.save_recovered_backup"] = new Entry("SAVE RECOVERED FROM BACKUP", "СОХРАНЕНИЕ ВОССТАНОВЛЕНО ИЗ РЕЗЕРВНОЙ КОПИИ"),
                ["ui.notice.save_recovered_interrupted"] = new Entry("INTERRUPTED SAVE RECOVERED", "ПРЕРВАННОЕ СОХРАНЕНИЕ ВОССТАНОВЛЕНО"),
                ["ui.common.back"] = new Entry("BACK", "НАЗАД"),
                ["ui.common.apply"] = new Entry("APPLY", "ПРИМЕНИТЬ"),
                ["ui.common.defaults"] = new Entry("DEFAULTS", "ПО УМОЛЧАНИЮ"),
                ["ui.common.reset_to_defaults"] = new Entry("RESET TO DEFAULTS", "СБРОСИТЬ ПО УМОЛЧАНИЮ"),
                ["ui.common.reset"] = new Entry("RESET", "СБРОСИТЬ"),
                ["ui.common.cancel"] = new Entry("CANCEL", "ОТМЕНИТЬ"),
                ["ui.common.revert"] = new Entry("REVERT CHANGES", "ОТМЕНИТЬ ИЗМЕНЕНИЯ"),
                ["ui.common.unavailable"] = new Entry("UNAVAILABLE", "НЕДОСТУПНО"),
                ["ui.common.not_available_short"] = new Entry("N/A", "Н/Д"),
                ["ui.common.adapter_pending"] = new Entry("ADAPTER PENDING", "НУЖЕН АДАПТЕР"),
                ["ui.common.reference_pending"] = new Entry("REFERENCE PENDING", "НЕТ РЕФЕРЕНСА"),
                ["ui.common.development_only"] = new Entry("DEVELOPMENT ONLY", "ТОЛЬКО ДЛЯ РАЗРАБОТКИ"),
                ["ui.common.on"] = new Entry("ON", "ВКЛ"),
                ["ui.common.off"] = new Entry("OFF", "ВЫКЛ"),
                ["ui.common.system_default"] = new Entry("System Default", "Системное устройство"),
                ["ui.greeting"] = new Entry("Have a nice day!", "Хорошего дня!"),
                ["ui.loading.title"] = new Entry("LOADING GAME", "ЗАГРУЗКА ИГРЫ"),
                ["ui.loading.detail"] = new Entry("Starting the prepared world and gameplay systems…", "Запуск подготовленного мира и игровых систем…"),
                ["ui.loading.save_detail"] = new Entry("Restoring the selected save before the world is revealed…", "Восстановление выбранного сохранения до показа мира…"),
                ["ui.loading.wait"] = new Entry("PLEASE WAIT…", "ПОЖАЛУЙСТА, ПОДОЖДИТЕ…"),
                ["ui.main.continue"] = new Entry("CONTINUE", "ПРОДОЛЖИТЬ"),
                ["ui.main.new_game"] = new Entry("NEW GAME", "НОВАЯ ИГРА"),
                ["ui.main.load_game"] = new Entry("LOAD GAME", "ЗАГРУЗИТЬ"),
                ["ui.main.credits"] = new Entry("CREDITS", "АВТОРЫ"),
                ["ui.main.quit"] = new Entry("QUIT", "ВЫЙТИ"),
                ["ui.main.settings"] = new Entry("SETTINGS", "НАСТРОЙКИ"),
                ["ui.main.mods"] = new Entry("MODS", "МОДЫ"),
                ["ui.main.dev_tools"] = new Entry("DEVELOPER TOOLS", "ИНСТРУМЕНТЫ РАЗРАБОТЧИКА"),
                ["ui.main.orbit_hint"] = new Entry("Hold LMB and drag to look around · Double-click to reset view", "Зажми ЛКМ и тяни — осмотреть · Двойной щелчок — вернуть ракурс"),
                ["ui.main.no_save"] = new Entry("Save storage unavailable", "Хранилище сохранений недоступно"),
                ["ui.main.no_valid_save"] = new Entry("No valid saved game", "Нет корректного сохранения"),
                ["ui.main.latest_save"] = new Entry("Latest save", "Последнее сохранение"),
                ["ui.main.car_color"] = new Entry("CAR COLOR", "ЦВЕТ МАШИНЫ"),
                ["ui.main.interior"] = new Entry("INTERIOR / TRUNK", "САЛОН / БАГАЖНИК"),
                ["ui.main.performance"] = new Entry("PERFORMANCE", "ПРОИЗВОДИТЕЛЬНОСТЬ"),
                ["ui.main.music_import"] = new Entry("IMPORT MUSIC FILES", "ИМПОРТ МУЗЫКИ"),
                ["ui.main.awaiting_sample"] = new Entry("Awaiting live sample", "Ожидание замера"),
                ["ui.main.live_frame_sample"] = new Entry("LIVE FRAME SAMPLE", "ТЕКУЩИЙ ЗАМЕР КАДРОВ"),
                ["ui.main.preview_unavailable"] = new Entry("Preview unavailable in 08A", "Предпросмотр недоступен в 08A"),
                ["ui.main.import_unavailable"] = new Entry("Importer not implemented", "Импорт пока не реализован"),
                ["ui.credits.body"] = new Entry(
                    "MY SUMMER CAR REMAKE\n\nPRIVATE DONOR-ASSISTED RECREATION\n\nENGINEERING & DIRECTION\nGAYmDev Studio\n\nUNITY 6 LTS / HDRP\nENVIRO 3 / WWISE\n\nReference pending — final credits will follow production content.",
                    "MY SUMMER CAR REMAKE\n\nЧАСТНАЯ РЕКОНСТРУКЦИЯ С ИСПОЛЬЗОВАНИЕМ ДОНОРА\n\nРАЗРАБОТКА И РУКОВОДСТВО\nGAYmDev Studio\n\nUNITY 6 LTS / HDRP\nENVIRO 3 / WWISE\n\nСостав авторов будет дополнен вместе с производственным контентом."),
                ["ui.category.graphics"] = new Entry("GRAPHICS", "ГРАФИКА"),
                ["ui.category.audio"] = new Entry("AUDIO", "ЗВУК"),
                ["ui.category.controls"] = new Entry("CONTROLS", "УПРАВЛЕНИЕ"),
                ["ui.category.gameplay"] = new Entry("GAMEPLAY", "ИГРОВОЙ ПРОЦЕСС"),
                ["ui.category.accessibility"] = new Entry("ACCESSIBILITY", "ДОСТУПНОСТЬ"),
                ["ui.category.mods"] = new Entry("MODS", "МОДЫ"),
                ["ui.graphics.preview"] = new Entry("PERFORMANCE PREVIEW", "ПРЕДПРОСМОТР ПРОИЗВОДИТЕЛЬНОСТИ"),
                ["ui.graphics.display_mode"] = new Entry("DISPLAY MODE", "РЕЖИМ ЭКРАНА"),
                ["ui.graphics.resolution"] = new Entry("RESOLUTION", "РАЗРЕШЕНИЕ"),
                ["ui.graphics.refresh"] = new Entry("REFRESH RATE", "ЧАСТОТА ОБНОВЛЕНИЯ"),
                ["ui.graphics.vsync"] = new Entry("V-SYNC", "ВЕРТИКАЛЬНАЯ СИНХРОНИЗАЦИЯ"),
                ["ui.graphics.camera"] = new Entry("CAMERA", "КАМЕРА"),
                ["ui.graphics.fov"] = new Entry("FIELD OF VIEW", "УГОЛ ОБЗОРА"),
                ["ui.graphics.draw_distance"] = new Entry("DRAW DISTANCE", "ДАЛЬНОСТЬ ПРОРИСОВКИ"),
                ["ui.graphics.anti_aliasing"] = new Entry("ANTI-ALIASING", "СГЛАЖИВАНИЕ"),
                ["ui.graphics.aa_preset"] = new Entry("AA PRESET", "ПРЕСЕТ СГЛАЖИВАНИЯ"),
                ["ui.graphics.aa.fxaa"] = new Entry("FXAA", "FXAA"),
                ["ui.graphics.aa.smaa"] = new Entry("SMAA", "SMAA"),
                ["ui.graphics.aa.taa"] = new Entry("TAA", "TAA"),
                ["ui.graphics.aa.maximum"] = new Entry("MAXIMUM / DLAA", "МАКСИМУМ / DLAA"),
                ["ui.graphics.aa.low"] = new Entry("LOW", "НИЗКИЙ"),
                ["ui.graphics.aa.medium"] = new Entry("MEDIUM", "СРЕДНИЙ"),
                ["ui.graphics.aa.high"] = new Entry("HIGH", "ВЫСОКИЙ"),
                ["ui.graphics.aa.ultra"] = new Entry("ULTRA", "УЛЬТРА"),
                ["ui.graphics.aa.custom"] = new Entry("CUSTOM", "СВОЙ"),
                ["ui.graphics.upscaling"] = new Entry("UPSCALING / SHARPENING", "МАСШТАБИРОВАНИЕ / РЕЗКОСТЬ"),
                ["ui.graphics.upscaler_quality"] = new Entry("UPSCALER QUALITY", "КАЧЕСТВО МАСШТАБИРОВАНИЯ"),
                ["ui.graphics.sharpening"] = new Entry("SHARPENING", "РЕЗКОСТЬ"),
                ["ui.graphics.dlss"] = new Entry("NVIDIA DLSS", "NVIDIA DLSS"),
                ["ui.graphics.dlss.quality"] = new Entry("QUALITY", "КАЧЕСТВО"),
                ["ui.graphics.dlss.balanced"] = new Entry("BALANCED", "СБАЛАНСИРОВАННЫЙ"),
                ["ui.graphics.dlss.performance"] = new Entry("PERFORMANCE", "ПРОИЗВОДИТЕЛЬНОСТЬ"),
                ["ui.graphics.dlss.ultra_performance"] = new Entry("ULTRA PERFORMANCE", "УЛЬТРАПРОИЗВОДИТЕЛЬНОСТЬ"),
                ["ui.graphics.dlss.dlaa"] = new Entry("DLAA", "DLAA"),
                ["ui.graphics.frame_generation"] = new Entry("FRAME GENERATION", "ГЕНЕРАЦИЯ КАДРОВ"),
                ["ui.graphics.quality"] = new Entry("QUALITY PRESET", "ПРЕСЕТ КАЧЕСТВА"),
                ["ui.graphics.quality.high_fidelity"] = new Entry("HIGH FIDELITY", "ВЫСОКОЕ КАЧЕСТВО"),
                ["ui.graphics.quality.balanced"] = new Entry("BALANCED", "СБАЛАНСИРОВАННЫЙ"),
                ["ui.graphics.quality.performant"] = new Entry("PERFORMANT", "ПРОИЗВОДИТЕЛЬНЫЙ"),
                ["ui.graphics.texture"] = new Entry("TEXTURE QUALITY", "КАЧЕСТВО ТЕКСТУР"),
                ["ui.graphics.shadow"] = new Entry("SHADOW QUALITY", "КАЧЕСТВО ТЕНЕЙ"),
                ["ui.graphics.reflection"] = new Entry("REFLECTION QUALITY", "КАЧЕСТВО ОТРАЖЕНИЙ"),
                ["ui.graphics.volumetric"] = new Entry("VOLUMETRIC QUALITY", "КАЧЕСТВО ОБЪЁМНЫХ ЭФФЕКТОВ"),
                ["ui.graphics.vegetation"] = new Entry("VEGETATION DENSITY", "ПЛОТНОСТЬ РАСТИТЕЛЬНОСТИ"),
                ["ui.graphics.post"] = new Entry("POST PROCESSING", "ПОСТОБРАБОТКА"),
                ["ui.graphics.motion_blur"] = new Entry("MOTION BLUR", "РАЗМЫТИЕ В ДВИЖЕНИИ"),
                ["ui.graphics.depth_of_field"] = new Entry("DEPTH OF FIELD", "ГЛУБИНА РЕЗКОСТИ"),
                ["ui.graphics.ray_tracing"] = new Entry("RAY TRACING", "ТРАССИРОВКА ЛУЧЕЙ"),
                ["ui.graphics.average_fps"] = new Entry("AVERAGE FPS", "СРЕДНИЙ FPS"),
                ["ui.graphics.one_low"] = new Entry("1% LOW", "1% LOW"),
                ["ui.graphics.vram"] = new Entry("VRAM USAGE", "ИСПОЛЬЗОВАНИЕ VRAM"),
                ["ui.graphics.live_backdrop"] = new Entry("LIVE WORLD BACKDROP", "ЖИВОЙ ФОН ИГРОВОГО МИРА"),
                ["ui.graphics.preview_helper"] = new Entry("Measured values only; unavailable metrics are not estimated.", "Только измеренные значения; недоступные метрики не оцениваются."),
                ["ui.audio.title"] = new Entry("AUDIO SETTINGS", "НАСТРОЙКИ ЗВУКА"),
                ["ui.audio.master"] = new Entry("MASTER VOLUME", "ОБЩАЯ ГРОМКОСТЬ"),
                ["ui.audio.engine"] = new Entry("ENGINE VOLUME", "ГРОМКОСТЬ ДВИГАТЕЛЯ"),
                ["ui.audio.environment"] = new Entry("ENVIRONMENT VOLUME", "ГРОМКОСТЬ ОКРУЖЕНИЯ"),
                ["ui.audio.voice"] = new Entry("VOICE VOLUME", "ГРОМКОСТЬ ГОЛОСОВ"),
                ["ui.audio.effects"] = new Entry("EFFECTS VOLUME", "ГРОМКОСТЬ ЭФФЕКТОВ"),
                ["ui.audio.music"] = new Entry("MUSIC VOLUME", "ГРОМКОСТЬ МУЗЫКИ"),
                ["ui.audio.radio"] = new Entry("RADIO VOLUME", "ГРОМКОСТЬ РАДИО"),
                ["ui.audio.ui"] = new Entry("UI SOUNDS", "ЗВУКИ ИНТЕРФЕЙСА"),
                ["ui.audio.weather"] = new Entry("WEATHER SOUNDS", "ЗВУКИ ПОГОДЫ"),
                ["ui.audio.thunder"] = new Entry("THUNDER SOUNDS", "ЗВУКИ ГРОМА"),
                ["ui.audio.reverb"] = new Entry("REVERB / AMBIENCE", "РЕВЕРБЕРАЦИЯ / АТМОСФЕРА"),
                ["ui.audio.dynamic"] = new Entry("DYNAMIC RANGE", "ДИНАМИЧЕСКИЙ ДИАПАЗОН"),
                ["ui.audio.subtitles"] = new Entry("SUBTITLES", "СУБТИТРЫ"),
                ["ui.audio.output"] = new Entry("AUDIO OUTPUT", "УСТРОЙСТВО ВЫВОДА"),
                ["ui.audio.test"] = new Entry("AUDIO TEST", "ПРОВЕРКА ЗВУКА"),
                ["ui.audio.test_unavailable"] = new Entry("Test event unavailable", "Тестовое событие недоступно"),
                ["ui.audio.profile"] = new Entry("SOUND PROFILE", "ЗВУКОВОЙ ПРОФИЛЬ"),
                ["ui.audio.backend"] = new Entry("BACKEND", "БЭКЕНД"),
                ["ui.audio.state"] = new Entry("STATE", "СОСТОЯНИЕ"),
                ["ui.audio.backend_ready"] = new Entry("Ready", "Готов"),
                ["ui.audio.backend_unavailable"] = new Entry("Unavailable", "Недоступен"),
                ["ui.audio.profile_tip"] = new Entry("Audio settings are applied only through the project IAudioBackend boundary.", "Настройки звука применяются только через проектную границу IAudioBackend."),
                ["ui.controls.keyboard"] = new Entry("KEYBOARD & MOUSE", "КЛАВИАТУРА И МЫШЬ"),
                ["ui.controls.action"] = new Entry("ACTION", "ДЕЙСТВИЕ"),
                ["ui.controls.primary"] = new Entry("PRIMARY", "ОСНОВНАЯ"),
                ["ui.controls.secondary"] = new Entry("SECONDARY", "ДОПОЛНИТЕЛЬНАЯ"),
                ["ui.controls.mouse"] = new Entry("MOUSE", "МЫШЬ"),
                ["ui.controls.gamepad"] = new Entry("GAMEPAD", "ГЕЙМПАД"),
                ["ui.controls.preview"] = new Entry("INPUT PREVIEW", "ПРОВЕРКА ВВОДА"),
                ["ui.controls.look_sensitivity"] = new Entry("Look Sensitivity", "Чувствительность обзора"),
                ["ui.controls.invert_y"] = new Entry("Invert Y-Axis", "Инверсия оси Y"),
                ["ui.controls.deadzone"] = new Entry("Trigger Deadzone", "Мёртвая зона"),
                ["ui.controls.vibration"] = new Entry("Controller Vibration", "Вибрация контроллера"),
                ["ui.controls.controller_layout"] = new Entry("CONTROLLER LAYOUT", "РАСКЛАДКА КОНТРОЛЛЕРА"),
                ["ui.controls.default_rebind"] = new Entry("DEFAULT / REBIND", "ПО УМОЛЧАНИЮ / ПЕРЕНАЗНАЧЕНИЕ"),
                ["ui.controls.input_mode"] = new Entry("CONTROLLER SUPPORT / INPUT MODE", "ПОДДЕРЖКА КОНТРОЛЛЕРА / РЕЖИМ ВВОДА"),
                ["ui.controls.auto_detect"] = new Entry("AUTO-DETECT", "АВТООПРЕДЕЛЕНИЕ"),
                ["ui.controls.selected_device"] = new Entry("Selected Device", "Активное устройство"),
                ["ui.controls.gamepad_sensitivity"] = new Entry("Look Sensitivity", "Чувствительность обзора"),
                ["ui.controls.rebinding"] = new Entry("PRESS A KEY — ESC TO CANCEL", "НАЖМИТЕ КЛАВИШУ — ESC ДЛЯ ОТМЕНЫ"),
                ["ui.controls.conflict"] = new Entry("Binding conflict — change cancelled", "Конфликт привязки — изменение отменено"),
                ["ui.controls.none"] = new Entry("—", "—"),
                ["ui.controls.key.escape"] = new Entry("Esc", "Esc"),
                ["ui.controls.key.space"] = new Entry("Space", "Пробел"),
                ["ui.controls.key.shift"] = new Entry("Shift", "Shift"),
                ["ui.controls.key.control"] = new Entry("Ctrl", "Ctrl"),
                ["ui.controls.key.enter"] = new Entry("Enter", "Enter"),
                ["ui.controls.key.backspace"] = new Entry("Backspace", "Backspace"),
                ["ui.controls.key.left"] = new Entry("Left", "Влево"),
                ["ui.controls.key.right"] = new Entry("Right", "Вправо"),
                ["ui.controls.key.up"] = new Entry("Up", "Вверх"),
                ["ui.controls.key.down"] = new Entry("Down", "Вниз"),
                ["ui.controls.key.page_up"] = new Entry("Page Up", "Страница вверх"),
                ["ui.controls.key.page_down"] = new Entry("Page Down", "Страница вниз"),
                ["ui.controls.steer_left"] = new Entry("Steering Left", "Руль влево"),
                ["ui.controls.steer_right"] = new Entry("Steering Right", "Руль вправо"),
                ["ui.controls.move_forward"] = new Entry("Move Forward", "Идти вперёд"),
                ["ui.controls.move_backward"] = new Entry("Move Backward", "Идти назад"),
                ["ui.controls.move_left"] = new Entry("Move Left", "Идти влево"),
                ["ui.controls.move_right"] = new Entry("Move Right", "Идти вправо"),
                ["ui.controls.crouch"] = new Entry("Crouch", "Присесть"),
                ["ui.controls.run"] = new Entry("Run", "Бежать"),
                ["ui.controls.jump"] = new Entry("Jump", "Прыгнуть"),
                ["ui.controls.zoom"] = new Entry("Zoom", "Приблизить взгляд"),
                ["ui.controls.forward_lean"] = new Entry("Lean Forward", "Наклониться вперёд"),
                ["ui.controls.throttle"] = new Entry("Throttle", "Газ"),
                ["ui.controls.brake"] = new Entry("Brake", "Тормоз"),
                ["ui.controls.clutch"] = new Entry("Clutch", "Сцепление"),
                ["ui.controls.gear_up"] = new Entry("Gear Up", "Повысить передачу"),
                ["ui.controls.gear_down"] = new Entry("Gear Down", "Понизить передачу"),
                ["ui.controls.ignition"] = new Entry("Ignition", "Зажигание"),
                ["ui.controls.handbrake"] = new Entry("Handbrake", "Ручной тормоз"),
                ["ui.controls.interact"] = new Entry("Interact", "Взаимодействовать"),
                ["ui.controls.throw"] = new Entry("Throw / Secondary", "Бросить / вторичное действие"),
                ["ui.controls.drop"] = new Entry("Drop Held Item", "Выпустить предмет"),
                ["ui.controls.place"] = new Entry("Place Held Item", "Поставить предмет"),
                ["ui.controls.rotate_held"] = new Entry("Free-Rotate Held Item", "Свободно вращать предмет"),
                ["ui.controls.tool_activate"] = new Entry("Use Tool", "Использовать инструмент"),
                ["ui.controls.urinate"] = new Entry("Urinate", "Мочиться"),
                ["ui.controls.wave"] = new Entry("Wave", "Помахать"),
                ["ui.controls.middle_finger"] = new Entry("Give the Finger", "Показать фак"),
                ["ui.controls.swear"] = new Entry("Swear", "Выругаться"),
                ["ui.controls.starter"] = new Entry("Starter", "Стартер"),
                ["ui.controls.vehicle_reset"] = new Entry("Reset Vehicle", "Вернуть машину"),
                ["ui.controls.inventory"] = new Entry("Inventory", "Инвентарь"),
                ["ui.controls.map"] = new Entry("Map", "Карта"),
                ["ui.controls.journal"] = new Entry("Journal", "Журнал"),
                ["ui.controls.pause"] = new Entry("Pause", "Пауза"),
                ["ui.gameplay.subtitle"] = new Entry("Adjust core gameplay experience and simulation preferences.", "Настройка игрового процесса и параметров симуляции."),
                ["ui.gameplay.autosave"] = new Entry("AUTOSAVE SLOTS", "СЛОТЫ АВТОСОХРАНЕНИЯ"),
                ["ui.gameplay.save_confirmation"] = new Entry("SAVE CONFIRMATION", "ПОДТВЕРЖДЕНИЕ СОХРАНЕНИЯ"),
                ["ui.gameplay.pause"] = new Entry("PAUSE BEHAVIOR", "ПОВЕДЕНИЕ ПАУЗЫ"),
                ["ui.gameplay.pause_freeze"] = new Entry("FREEZE GAME", "ОСТАНОВИТЬ ИГРУ"),
                ["ui.gameplay.hud"] = new Entry("HUD MODE", "РЕЖИМ HUD"),
                ["ui.gameplay.fps_counter"] = new Entry("FPS COUNTER", "СЧЁТЧИК FPS"),
                ["ui.gameplay.units"] = new Entry("MILEAGE UNITS", "ЕДИНИЦЫ ИЗМЕРЕНИЯ"),
                ["ui.gameplay.language"] = new Entry("LANGUAGE", "ЯЗЫК"),
                ["ui.gameplay.difficulty"] = new Entry("DIFFICULTY PRESET", "СЛОЖНОСТЬ"),
                ["ui.gameplay.fatigue"] = new Entry("FATIGUE EFFECTS", "ЭФФЕКТЫ УСТАЛОСТИ"),
                ["ui.gameplay.alcohol"] = new Entry("ALCOHOL EFFECTS INTENSITY", "ИНТЕНСИВНОСТЬ АЛКОГОЛЬНЫХ ЭФФЕКТОВ"),
                ["ui.gameplay.hints"] = new Entry("HINTS", "ПОДСКАЗКИ"),
                ["ui.gameplay.tutorial"] = new Entry("TUTORIAL PROMPTS", "ОБУЧАЮЩИЕ ПОДСКАЗКИ"),
                ["ui.gameplay.outlines"] = new Entry("INTERACTION OUTLINES", "ОБВОДКА ВЗАИМОДЕЙСТВИЙ"),
                ["ui.gameplay.camera_shake"] = new Entry("CAMERA SHAKE", "ТРЯСКА КАМЕРЫ"),
                ["ui.gameplay.developer"] = new Entry("DEVELOPER MODE VISIBILITY", "ОТОБРАЖЕНИЕ DEV-РЕЖИМА"),
                ["ui.gameplay.profile"] = new Entry("PROFILE", "ПРОФИЛЬ"),
                ["ui.gameplay.manage_profiles"] = new Entry("MANAGE PROFILES", "УПРАВЛЕНИЕ ПРОФИЛЯМИ"),
                ["ui.gameplay.immersion"] = new Entry("IMMERSION LEVEL", "УРОВЕНЬ ПОГРУЖЕНИЯ"),
                ["ui.gameplay.summary"] = new Entry("SUMMARY", "СВОДКА"),
                ["ui.gameplay.custom_summary"] = new Entry("CUSTOM", "ПОЛЬЗОВАТЕЛЬСКИЙ"),
                ["ui.gameplay.summary_not_score"] = new Entry("Summary of selected options — not a gameplay score.", "Сводка выбранных параметров, а не игровая оценка."),
                ["ui.gameplay.apply_changes"] = new Entry("APPLY CHANGES", "ПРИМЕНИТЬ ИЗМЕНЕНИЯ"),
                ["ui.access.title"] = new Entry("ACCESSIBILITY", "ДОСТУПНОСТЬ"),
                ["ui.access.scale"] = new Entry("UI SCALE", "МАСШТАБ ИНТЕРФЕЙСА"),
                ["ui.access.contrast"] = new Entry("HIGH CONTRAST", "ВЫСОКИЙ КОНТРАСТ"),
                ["ui.access.motion"] = new Entry("REDUCED MOTION", "УМЕНЬШЕННОЕ ДВИЖЕНИЕ"),
                ["ui.access.toggle_hold"] = new Entry("TOGGLE HOLD ACTIONS", "ПЕРЕКЛЮЧАТЕЛЬ УДЕРЖАНИЯ"),
                ["ui.access.color_cues"] = new Entry("COLOR-INDEPENDENT CUES", "ПОДСКАЗКИ НЕ ТОЛЬКО ЦВЕТОМ"),
                ["ui.access.captions"] = new Entry("SOUND CAPTIONS", "ТЕКСТОВЫЕ ОПИСАНИЯ ЗВУКОВ"),
                ["ui.mods.title"] = new Entry("MODS", "МОДЫ"),
                ["ui.mods.unavailable"] = new Entry("Mod support is not available in this build.", "Поддержка модов в этой сборке недоступна."),
                ["ui.pause.title"] = new Entry("PAUSED", "ПАУЗА"),
                ["ui.pause.resume"] = new Entry("RESUME", "ПРОДОЛЖИТЬ"),
                ["ui.pause.save_status"] = new Entry("SAVE / LOAD STATUS", "СОСТОЯНИЕ СОХРАНЕНИЯ"),
                ["ui.pause.main_menu"] = new Entry("RETURN TO MAIN MENU", "ВЕРНУТЬСЯ В МЕНЮ"),
                ["ui.confirmation.title"] = new Entry("CONFIRM EXIT", "ПОДТВЕРДИТЕ ВЫХОД"),
                ["ui.confirmation.quit_body"] = new Entry("Quit to desktop? Unsaved progress may be lost.", "Выйти на рабочий стол? Несохранённый прогресс может быть потерян."),
                ["ui.confirmation.cancel"] = new Entry("CANCEL", "ОТМЕНА"),
                ["ui.confirmation.quit"] = new Entry("QUIT", "ВЫЙТИ"),
                ["ui.save_status.title"] = new Entry("SAVE / LOAD STATUS", "СТАТУС СОХРАНЕНИЯ"),
                ["ui.save_status.detail"] = new Entry("Native save status", "Состояние нативных сохранений"),
                ["ui.save_status.no_provider"] = new Entry("SAVE SYSTEM UNAVAILABLE", "СИСТЕМА СОХРАНЕНИЙ НЕДОСТУПНА"),
                ["ui.save_status.provider_detail"] = new Entry("No native save service was supplied by this composition.", "Эта конфигурация не предоставила нативный сервис сохранений."),
                ["ui.save_status.no_slots"] = new Entry("NO SAVED GAMES", "СОХРАНЕНИЙ НЕТ"),
                ["ui.save_status.no_slots_detail"] = new Entry("Start a new game before creating a manual save.", "Начните новую игру, чтобы создать ручное сохранение."),
                ["ui.save_status.no_slots_pause_detail"] = new Entry("Create the first manual save in the configured slot.", "Создайте первое ручное сохранение в настроенном слоте."),
                ["ui.save_status.empty"] = new Entry("EMPTY", "ПУСТО"),
                ["ui.save_status.empty_detail"] = new Entry("This slot is empty. Start a game to create a save here.", "Этот слот пуст. Начните игру, чтобы создать здесь сохранение."),
                ["ui.save_status.empty_pause_detail"] = new Entry("This slot is empty and ready for a manual save.", "Этот слот пуст и готов для ручного сохранения."),
                ["ui.save_status.invalid"] = new Entry("INVALID", "ПОВРЕЖДЕНО"),
                ["ui.save_status.invalid_detail"] = new Entry("This slot failed validation and cannot be loaded.", "Слот не прошёл проверку и не может быть загружен."),
                ["ui.save_status.slot"] = new Entry("SLOT", "СЛОТ"),
                ["ui.save_status.updated"] = new Entry("UPDATED", "ОБНОВЛЕНО"),
                ["ui.save_status.game_time"] = new Entry("GAME TIME", "ИГРОВОЕ ВРЕМЯ"),
                ["ui.save_status.location"] = new Entry("LOCATION", "МЕСТО"),
                ["ui.save_status.save"] = new Entry("SAVE", "СОХРАНИТЬ"),
                ["ui.save_status.load"] = new Entry("LOAD", "ЗАГРУЗИТЬ"),
                ["ui.save_status.saving"] = new Entry("SAVING…", "СОХРАНЕНИЕ…"),
                ["ui.save_status.loading"] = new Entry("LOADING…", "ЗАГРУЗКА…"),
                ["ui.save_status.refreshing"] = new Entry("REFRESHING SLOTS…", "ОБНОВЛЕНИЕ СЛОТОВ…"),
                ["ui.save_status.saved"] = new Entry("SAVE COMPLETED", "ИГРА СОХРАНЕНА"),
                ["ui.save_status.loaded"] = new Entry("LOAD COMPLETED", "ИГРА ЗАГРУЖЕНА"),
                ["ui.save_status.failed"] = new Entry("OPERATION FAILED:", "ОШИБКА:"),
                ["ui.save_status.recovered"] = new Entry("A VALID BACKUP WAS RECOVERED", "ВОССТАНОВЛЕНА КОРРЕКТНАЯ РЕЗЕРВНАЯ КОПИЯ"),
                ["ui.hud.time"] = new Entry("TIME", "ВРЕМЯ"),
                ["ui.hud.day"] = new Entry("DAY", "ДЕНЬ"),
                ["ui.hud.date"] = new Entry("DATE", "ДАТА"),
                ["ui.hud.money"] = new Entry("MONEY", "ДЕНЬГИ"),
                ["ui.hud.thirst"] = new Entry("THIRST", "ЖАЖДА"),
                ["ui.hud.hunger"] = new Entry("HUNGER", "ГОЛОД"),
                ["ui.hud.stress"] = new Entry("STRESS", "СТРЕСС"),
                ["ui.hud.urine"] = new Entry("URINE", "НУЖДА"),
                ["ui.hud.fatigue"] = new Entry("FATIGUE", "УТОМЛЕНИЕ"),
                ["ui.hud.dirtiness"] = new Entry("DIRTINESS", "НЕОПРЯТНОСТЬ"),
                ["ui.notice.saved"] = new Entry("Settings applied", "Настройки применены"),
                ["ui.notice.defaults"] = new Entry("Defaults loaded — Apply to confirm", "Загружены значения по умолчанию — нажмите Применить"),
                ["ui.notice.reverted"] = new Entry("Pending changes reverted", "Изменения отменены"),
                ["ui.notice.gameplay_activation_failed"] = new Entry("GAMEPLAY START FAILED", "НЕ УДАЛОСЬ ЗАПУСТИТЬ ИГРУ"),
                ["ui.notice.game_saved"] = new Entry("GAME SAVED", "ИГРА СОХРАНЕНА"),
                ["ui.notice.save_failed"] = new Entry("SAVE FAILED", "НЕ УДАЛОСЬ СОХРАНИТЬ ИГРУ"),
                ["ui.notice.load_failed"] = new Entry("LOAD FAILED", "НЕ УДАЛОСЬ ЗАГРУЗИТЬ ИГРУ"),
                ["ui.notice.save_recovered"] = new Entry("SAVE RECOVERED FROM BACKUP", "СОХРАНЕНИЕ ВОССТАНОВЛЕНО ИЗ РЕЗЕРВНОЙ КОПИИ"),
                ["ui.value.display.windowed"] = new Entry("WINDOWED", "ОКОННЫЙ"),
                ["ui.value.display.borderless"] = new Entry("BORDERLESS FULLSCREEN", "ПОЛНОЭКРАННЫЙ БЕЗ РАМОК"),
                ["ui.value.display.exclusive"] = new Entry("EXCLUSIVE FULLSCREEN", "ЭКСКЛЮЗИВНЫЙ ПОЛНОЭКРАННЫЙ"),
                ["ui.value.dynamic.night"] = new Entry("NIGHT", "НОЧНОЙ"),
                ["ui.value.dynamic.standard"] = new Entry("STANDARD", "СТАНДАРТНЫЙ"),
                ["ui.value.dynamic.wide"] = new Entry("WIDE", "ШИРОКИЙ"),
                ["ui.value.hud.off"] = new Entry("OFF", "ВЫКЛ"),
                ["ui.value.hud.contextual"] = new Entry("CONTEXTUAL", "КОНТЕКСТНЫЙ"),
                ["ui.value.hud.full"] = new Entry("FULL", "ПОЛНЫЙ"),
                ["ui.value.units.metric"] = new Entry("KILOMETERS", "КИЛОМЕТРЫ"),
                ["ui.value.units.imperial"] = new Entry("MILES", "МИЛИ"),
                ["ui.value.language.english"] = new Entry("ENGLISH", "АНГЛИЙСКИЙ"),
                ["ui.value.language.russian"] = new Entry("RUSSIAN", "РУССКИЙ"),
            };

        public string LocaleId { get; set; } = "en-US";

        public string Get(string id)
        {
            if (!entries.TryGetValue(id, out Entry value))
            {
                return id;
            }

            return LocaleId.StartsWith("ru", StringComparison.OrdinalIgnoreCase)
                ? value.Russian
                : value.English;
        }

        private readonly struct Entry
        {
            public Entry(string english, string russian)
            {
                English = english;
                Russian = russian;
            }

            public string English { get; }

            public string Russian { get; }
        }
    }
}
