using System;
using System.Collections.Generic;
using MSC.World.Vegetation;
using UnityEngine;

namespace MSC.Editor.Vegetation
{
    /// <summary>Checks saved ownership and evidence for the categories regenerated by this pilot.</summary>
    public sealed class MapVegetationCaptureScope
    {
        private static readonly MapVegetationCategories[] Categories =
        {
            MapVegetationCategories.OriginalTrees, MapVegetationCategories.BoundaryForest,
            MapVegetationCategories.GrassCoverage, MapVegetationCategories.ShrubsAndUndergrowth
        };
        private readonly List<string> errors = new List<string>();
        private readonly List<string> preservedCategoryFingerprints = new List<string>();

        public string Fingerprint { get; private set; }
        public bool IsValid => errors.Count == 0;
        public bool RequiresDeepBoundaryView { get; private set; }
        public int RequiredViewCount => RequiresDeepBoundaryView ? 5 : 4;
        public IReadOnlyList<string> Errors => errors;
        public IReadOnlyList<string> PreservedCategoryFingerprints => preservedCategoryFingerprints;

        public static MapVegetationCaptureScope Evaluate(MapVegetationCategories selected, string cellId,
            IReadOnlyList<GameObject> roots, bool requireRepresentative = true)
        {
            if (roots == null) throw new ArgumentNullException(nameof(roots));
            var result = new MapVegetationCaptureScope();
            var counts = new Dictionary<MapVegetationCategories, int>();
            if (selected == MapVegetationCategories.None || (selected & ~MapVegetationCategories.All) != 0)
                result.errors.Add("Capture requires a valid selected vegetation category scope.");
            foreach (GameObject root in roots)
            {
                GeneratedVegetationGroup group = root != null ? root.GetComponent<GeneratedVegetationGroup>() : null;
                if (group == null || group.GeneratorId != MapVegetationRebuildOptions.GeneratorId) continue;
                if (group.CellId != cellId) result.errors.Add("Generated root belongs to another cell: " + root.name);
                if (!Enum.TryParse(group.Category, out MapVegetationCategories category) || Array.IndexOf(Categories, category) < 0)
                { result.errors.Add("Generated root has an invalid category: " + root.name); continue; }
                if ((selected & category) == 0)
                {
                    result.preservedCategoryFingerprints.Add(group.Category + ":" + group.Fingerprint);
                    continue;
                }
                if (counts.ContainsKey(category))
                { result.errors.Add("Duplicate selected category root: " + category); continue; }
                int count = category == MapVegetationCategories.GrassCoverage
                    ? CountGrass(root)
                    : CountWoody(root, category, result.errors);
                counts.Add(category, count);
                if (string.IsNullOrEmpty(group.Fingerprint)) result.errors.Add("Selected category has no fingerprint: " + category);
                if (result.Fingerprint == null) result.Fingerprint = group.Fingerprint;
                else if (result.Fingerprint != group.Fingerprint)
                    result.errors.Add("Selected generated categories have different fingerprints.");
            }
            foreach (MapVegetationCategories category in Categories)
            {
                if ((selected & category) == 0) continue;
                if (!counts.TryGetValue(category, out int count)) result.errors.Add("Missing selected category root: " + category);
                else if (requireRepresentative && count == 0) result.errors.Add("Selected pilot category has no saved instances: " + category);
            }
            result.RequiresDeepBoundaryView = counts.TryGetValue(MapVegetationCategories.BoundaryForest, out int boundaryCount) && boundaryCount > 0;
            return result;
        }

        private static int CountGrass(GameObject root)
        {
            int count = 0;
            foreach (VegetationWorldRenderer renderer in root.GetComponentsInChildren<VegetationWorldRenderer>(true))
            {
                if (!renderer.enabled || renderer.Catalog == null) continue;
                foreach (VegetationCellAsset cell in renderer.Catalog.Cells)
                {
                    if (cell == null) continue;
                    foreach (VegetationTileRecord tile in cell.Tiles)
                        if (tile != null) count += tile.TotalInstanceCount;
                }
            }
            return count;
        }

        private static int CountWoody(
            GameObject root,
            MapVegetationCategories category,
            ICollection<string> validationErrors)
        {
            PackedWoodyCellRenderer renderer =
                root.GetComponent<PackedWoodyCellRenderer>();
            if (renderer == null || renderer.CellAsset == null)
                return root.transform.childCount;

            PackedWoodyCategory expectedCategory = category switch
            {
                MapVegetationCategories.OriginalTrees =>
                    PackedWoodyCategory.OriginalTree,
                MapVegetationCategories.BoundaryForest =>
                    PackedWoodyCategory.BoundaryForest,
                MapVegetationCategories.ShrubsAndUndergrowth =>
                    PackedWoodyCategory.ShrubOrUndergrowth,
                _ => throw new ArgumentOutOfRangeException(nameof(category), category, null)
            };
            if (renderer.CellAsset.Category != expectedCategory)
                validationErrors.Add("Packed woody category differs from root: " + category);
            foreach (string error in renderer.CellAsset.ValidateConfiguration())
                validationErrors.Add(category + ": " + error);
            return renderer.CellAsset.InstanceCount;
        }
    }
}
